### ISSUE TITLE
final_data.csv  file is unknown, and the checkpoint download URL is unavailable

### ISSUE THREAD

**Issue by Taocunguo** [patrick-batman/Med-ViLT#1]
May I ask if the author can give me an answer to these two questions that bother me so much? from tools.registry import registry What is this

**Comment by patrick-batman** [comment]
- uploaded final_data.csv
- fixed contrastive loss

**Comment by Taocunguo** [comment]
> * uploaded final_data.csv
> * fixed contrastive loss

thanks, one more question，In the data_augmenttation.ipynb file, synonyms['premise'], what is 'premise' that is not specified in the file

**Comment by Taocunguo** [comment]
thanks, one more question，In the data_augmenttation.ipynb file, synonyms['premise'], what is 'premise' that is not specified in the file
