### ISSUE TITLE
thanks, one more question，In the data_augmenttation.ipynb file, synonyms['premise'], what is 'premise' that is not specified in the file- uploaded final_data.csv

### ISSUE THREAD

**Issue by Taocunguo** [patrick-batman/Med-ViLT#2]
- uploaded final_data.csv
- fixed contrastive loss

_Originally posted by @patrick-batman in https://github.com/patrick-batman/Med-ViLT/issues/1#issuecomment-1885286012_

**Comment by Taocunguo** [comment]
thanks, one more question，In the data_augmenttation.ipynb file, synonyms['premise'], what is 'premise' that is not specified in the file

**Comment by patrick-batman** [comment]
it was used during paraphrasing of original questions of VQA-RAD dataset; you can generate your own questions
